version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.6
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: Install gem dependencies
          command: gem install bundler && bundle install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
